--- 
title: "HarvardX - Data Science - PH125.9x - MovieLens project"
subtitle: "Project part of the Capstone course"
author: "Ioannis Barbanas - https://github.com/barbanas/movielens_project"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
site: bookdown::bookdown_site
output: 
  bookdown::pdf_book:
    toc: true
    toc_depth: 3
    number_sections: true
    suppress_warnings: true
  html_document: 
    number_sections: true
    suppress_warnings: true

documentclass: report
geometry: "a4paper,left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
lot: no
lof: no

bibliography: [packages.bib]
link-citations: yes
colorlinks: yes

github-repo: barbanas/HarvardX-Movielens
description: "HarvardX - Data Science - PH125.9x - MovieLens project"
---


```{r child = '1_Introduction.rmd'}
```

```{r child = '2_Pre-processing.rmd'}
```

```{r child = '3_Data_exploration-visualisation.rmd'}
```

```{r child = '4_Setting_the_baseline.rmd'}
```

```{r child = '5_Machine_Learning_Models_Part_I.rmd'}
```

```{r child = '6_Machine_Learning_Models_Part_II.rmd'}
```

```{r child = '7_Conclusion.rmd'}
```

```{r child = '8_Appendix.rmd'}
```

```{r child = '9_References.rmd'}
```